services:
  mcp-server:
    image: ghcr.io/adamsi/gisma-agent/gisma-mcp-server:latest
    container_name: mcp-server
    restart: always
    networks:
      - default
      - dev_default
    expose:
      - "8081"
    env_file:
      - .env

  agent:
    image: ghcr.io/adamsi/gisma-agent/gisma-agent-server:latest
    container_name: gisma-agent
    restart: always
    networks:
      - default
      - dev_default
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg15
    container_name: gisma-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  dev_default:
    external: true

volumes:
  pgdata: